<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Prueba Backend</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
</head>
<body>
    <div class="container">
        <h2 class="mt-3">PART 01</h2>
        <div class="card">
            <div class="card-body">
                <h4>Problem 1</h4>                
                <div style="">
                    <div class="form-group row">
                        <label class="col-4 col-form-label">Enter a text</label>
                        <div class="col-6">
                            <input type="text" id="input1" class="form-control">
                        </div>
                        <div class="col-2 text-right">
                            <button id="process1" class="btn btn-success process">Process</button>
                        </div>
                    </div>            
                    <div class="form-group  row">
                        <div class="col-12">
                            <textarea id="solution1"  readonly class="form-control "></textarea>    
                        </div>                
                    </div>
                </div>
            </div>            
        </div>
        <div class="card mt-3">
            <div class="card-body">
                <h4>Problem 2</h4>
                <div style="">
                    <div class="form-group row">
                        <label class="col-4 col-form-label">Enter a text</label>
                        <div class="col-6">
                            <input type="text" id="input2" class="form-control">
                        </div>
                        <div class="col-2 text-right">
                            <button id="process2" class="btn btn-success process">Process</button>
                        </div>
                    </div>            
                    <div class="form-group  row">
                        <div class="col-12">
                            <textarea id="solution2" placeholder="num1, num2, num3, ..." readonly class="form-control"></textarea>    
                        </div>                
                    </div>
                </div>
            </div>            
        </div>
        <div class="card mt-3">
            <div class="card-body">
                <h4>Problem 3</h4>
                <div style="">
                    <div class="form-group row">
                        <label class="col-4 col-form-label">Enter a text</label>
                        <div class="col-6">
                            <input type="text" id="input3" class="form-control">
                        </div>
                        <div class="col-2 text-right">
                            <button id="process3" class="btn btn-success process">Process</button>
                        </div>
                    </div>            
                    <div class="form-group  row">
                        <div class="col-12">
                            <textarea id="solution3" readonly class="form-control"></textarea>    
                        </div>                
                    </div>
                </div>
            </div>            
        </div>

        <hr>
        
        <h2>PART 02</h2>
        <div class="card mt-3">
            <div class="card-body">
                <h4>All Developers</h4>                    
                    <div class="row">
                        <label class="col-2 col-form-label">Search for Email</label>
                        <div class="col-8">
                            <input name="email" id="email" type="text" class="form-control">
                        </div>
                        <div class="col-2">
                            <button id="btnsearch" class="btn btn-primary">Buscar!</button>
                        </div>            
                    </div>
                    
                    <hr>
                    <table class="table table-bordered table-striped table-hover">
                        <thead class="thead-inverse">
                            <tr>
                                <th>Name</th>
                                <th>Email</th>
                                <th>Position</th>
                                <th>Salary</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php if(isset($developers)) {?>
                                <?php foreach($developers as $developer): ?>
                                <tr>
                                    <td><?=$developer["name"] ?></td>
                                    <td><?=$developer["email"] ?></td>
                                    <td><?=$developer["position"] ?></td>
                                    <td><?=$developer["salary"] ?></td>
                                    <td><a href="<?=$router->pathFor('developer-detail', ['id' => $developer["id"]])?>">View</a></td>
                                </tr>
                                <?php endforeach ?>
                            <?php } ?>
                        </tbody>
                    </table>
            </div>
        </div>
    </div>    
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script type="text/javascript">
    $(function() {
        $('#input3').keypress(function (e){
            if (e.keyCode != 40 && e.keyCode != 41) { return false; } 
        });

        $('#btnsearch').click( function (){
            $.ajax({
                data: {"email" : $("#email").val()},
                url: "search",
                type: 'GET',
                dataType: 'JSON',
                success: function (data) {
                    $('.table-bordered tbody tr').remove();
                    $(data).each(function () {
                        var element = document.createElement('tr');
                        $(element).data('dataItem', this);                        
                        var html = '<tr><td>' + this.name +'</td>'+'<td>' + this.email + '</td>'
                                    +'<td>' + this.position  +'</td>'+'<td>' + this.salary  +'</td><td><a href="developer/' + this.id  +'">View</a></td></tr>';

                        console.log(html);
                        
                        $('.table-bordered tbody').append(html);

                    });
                        //solution.html(response);
                }
            });
        });

        $('.process').click( function (){
            
            var url="";var parameter="";var solution;
            switch($(this).attr('id')) {
                case 'process1': url="problem1";parameter=$('#input1').val();solution=$("#solution1");break;
                case 'process2': url="problem2";parameter=$('#input2').val();solution=$("#solution2");break;
                case 'process3': url="problem3";parameter=$('#input3').val();solution=$("#solution3");break;
            }
            $.ajax({
                data: {"value" : parameter},
                type: "GET",
                url: url,
                beforeSend: function () {
                        solution.html("Processing, wait a moment please...");
                },
                success:  function (response) {
                        solution.html(response);
                }
            });
        });
    });
    
</script>
</script>
</body>
</html>

