<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Developer - Prueba Backend</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
</head>
</head>
<body>
    <div class="container">
        <h4 class="mt-5">Developer: </h4>
        <div class="row">
            <label class="col-2 col-form-label font-weight-bold">Name</label>
            <label class="col-4 col-form-label"><?=$developerdetail["name"] ?></label>
        </div>
        <div class="row">
            <label class="col-2 col-form-label font-weight-bold">Email</label>
            <label class="col-4 col-form-label"><?=$developerdetail["email"] ?></label>
        </div>
        <div class="row">
            <label class="col-2 col-form-label font-weight-bold">Phone</label>
            <label class="col-4 col-form-label"><?=$developerdetail["phone"] ?></label>
        </div>
        <div class="row">
            <label class="col-2 col-form-label font-weight-bold">Address</label>
            <label class="col-4 col-form-label"><?=$developerdetail["address"] ?></label>
        </div>
        <div class="row">
            <label class="col-2 col-form-label font-weight-bold">Position</label>
            <label class="col-4 col-form-label"><?=$developerdetail["position"] ?></label>
        </div>
        <div class="row">
            <label class="col-2 col-form-label font-weight-bold">Salary</label>
            <label class="col-4 col-form-label"><?=$developerdetail["salary"] ?></label>
        </div>
        <div class="row">
            <label class="col-2 col-form-label font-weight-bold">Skills</label>
            <div class="col-4 ">
                <ul class="pl-3">
                    <?php foreach($developerdetail["skills"] as $skill): ?>
                    <li><?=$skill["skill"] ?></li>
                    <?php endforeach ?>
                </ul>    
            </div>
            
        </div>
    </div>
</body>

</html>
